#!/bin/bash

# Migration Helper Script
# This script helps you migrate from old Supabase to new Supabase project

echo "=========================================="
echo "Supabase Migration Helper"
echo "=========================================="
echo ""
echo "Old Project: emscbdwqqnvcjskrdmzp (Lovable)"
echo "New Project: joafocyskbvvfltwfefu (adamsmyth)"
echo ""
echo "This script will guide you through the migration."
echo ""

# Step 1: Check migrations
echo "Step 1: Database Migrations"
echo "---------------------------"
echo "You need to run these migration files in order:"
echo ""
echo "1. 20251217035005_... - stock_quotes table"
echo "2. 20260105084126_... - user_stock_theories, user_research_xp"
echo "3. 20260116232543_... - quiz_responses, archetype_stats"
echo "4. 20260117043621_... - user_nudges policy (table might already exist)"
echo "5. 20260121040144_... - referral_codes"
echo "6. 20260121040311_... - referral function"
echo "7. 20260121040417_... - referral policies"
echo "8. 20260121040446_... - referral grants"
echo "9. 20260122000000_... - catalysts (already done ✅)"
echo ""
echo "Open: https://supabase.com/dashboard/project/joafocyskbvvfltwfefu/sql/new"
echo "Copy each migration file and run it."
echo ""
read -p "Press Enter when you've run all migrations..."

# Step 2: Edge Functions
echo ""
echo "Step 2: Edge Functions"
echo "---------------------"
echo "Deploy these functions to new project:"
echo ""
echo "1. fetch-stock-data"
echo "2. refresh-stock-data"
echo "3. stock-chart"
echo "4. stock-analysis"
echo "5. ai-advisor-chat"
echo "6. company-advisor-chat"
echo "7. analyze-learning"
echo "8. fetch-catalysts (already done ✅)"
echo ""
echo "Go to: https://supabase.com/dashboard/project/joafocyskbvvfltwfefu/functions"
echo "For each function: Create → Copy code from supabase/functions/[name]/index.ts → Deploy"
echo ""
read -p "Press Enter when all functions are deployed..."

# Step 3: Secrets
echo ""
echo "Step 3: Secrets"
echo "---------------"
echo "Add these secrets to new project:"
echo ""
echo "1. FINNHUB_API_KEY (already done ✅)"
echo "2. ALPHA_VANTAGE_API_KEY (check old project if needed)"
echo "3. LOVABLE_API_KEY (check old project if needed)"
echo ""
echo "Go to: https://supabase.com/dashboard/project/joafocyskbvvfltwfefu/settings/functions"
echo "Check old project for secrets: https://supabase.com/dashboard/project/emscbdwqqnvcjskrdmzp/settings/functions"
echo ""
read -p "Press Enter when secrets are configured..."

# Step 4: Verify
echo ""
echo "Step 4: Verification"
echo "-------------------"
echo "Check that everything is set up:"
echo ""
echo "✅ All tables exist in new project"
echo "✅ All Edge Functions deployed"
echo "✅ All secrets configured"
echo "✅ .env file updated (already done ✅)"
echo ""
echo "Restart your dev server: npm run dev"
echo ""
echo "Migration complete! 🎉"
